### ISSUE TITLE
A case for raise*

### ISSUE THREAD

**Issue by 1st1** [python/exceptiongroups#7]
This builds on top of what's defined in [here](https://github.com/python/exceptiongroups/blob/3ebd257d94432ccae3120db3dcb6e0970960b6bc/except_star.md) (permalink)

-----

According to the latest spec, using `raise e` or `raise` inside an `except*` clause wouldn't flatten the tree of errors, e.g.:

```python
try:
  raise ExceptionGroup(
    ValueError('a'),
    TypeError('b'),
    ExceptionGroup(
      TypeError('c'),
      KeyError('d')
    )
  )
except *TypeError as e:
  raise  # or "raise e"

# would both terminate with:
#
#  ExceptionGroup(
#    ValueError('a'),
#    TypeError('b'),
#    ExceptionGroup(
#      TypeError('c'),
#      KeyError('d')
#    )
#  )
```

But when raising an `ExceptionGroup()` instance manually the tree would be flattened:

```python
try:
  raise ExceptionGroup(
    ValueError('a'),
    TypeError('b'),
    ExceptionGroup(
      TypeError('c'),
      KeyError('d')
    )
  )
except *TypeError as e:
  raise ExceptionGroup(*e)

# would terminate with:
#
#  ExceptionGroup(
#    ValueError('a'),
#    ExceptionGroup(
#      TypeError('b'),
#      TypeError('c'),
#    ),
#    ExceptionGroup(
#      KeyError('d')
#    )
#  )
```

This makes the case of "I only want to handle one or few exceptions from the group and re-raise all others without flattening them" a bit problematic.  But what if we could use `raise *` syntax for that:

```python
try:
  raise ExceptionGroup(
    ValueError('a'),
    TypeError('b'),
    ExceptionGroup(
      TypeError('c'),
      KeyError('d')
    )
  )
except *TypeError as e:
  er1, *rest = e

  log(er1)  # we'd like to ignore er1, just log it

  raise *rest

# would both terminate with:
#
#  ExceptionGroup(
#    ValueError('a'),
#    ExceptionGroup(
#      TypeError('c'),
#      KeyError('d')
#    )
#  )
```

**Comment by 1st1** [comment]
We can even construct a relatively realistic example for this: ignoring all `OSError(errno=ESOMETHING)` from the group preserving where all `OSError`s positions in the group tree.

**Comment by gvanrossum** [comment]
Alternatively, we could have a split operation like in Trio's [MultiError v2](https://github.com/python-trio/trio/issues/611) design, which takes a predicate and returns two MultiError instances with the same substructure. Then if we were to use that same split operation to split off the exceptions matching the except clause, `e` would have the same structure, and so would `er1` and `rest` (when using that split operation). The merge operation should do the right thing so that plain `raise e` and bare `raise` would result in the right thing happening, so you wouldn't need `raise *`.

The split operation should be recursive, e.g. (untested):
```py
class MultiError(BaseException):
    def split(self, pred):
        a = None
        b = None
        for e in self.inner_exceptions:
            if isinstance(e, MultiError):
                a1, b1 = e.split(pred)
                a = join(a, a1)
                b = join(b, b1)
            elif pred(e):
                a = join(a, e)
            else:
                b = join(b, e)
        return a, b
```
where
```py
def join(a, e):
    if e is None:
        return a
    if a is None:
        a = MultiError()
    a.inner_exceptions.append(e)
    return a
```

**Comment by iritkatriel** [comment]
ISTM that we don't really have a choice in the matter - the split operation has to preserve the nested structure because otherwise the tracebacks are wrong.  Exceptions that belong to the same ExceptionGroup share the traceback of the group, and then they split. If we offer a flatten operation for Exception groups, then it needs to also set all the tracebacks to None.

**Comment by iritkatriel** [comment]
Related to the above - I think this example from the current document is incorrect. The KeyError should not be merged into the EG of the TypeError, because it doesn't have that EG's traceback.

```
try:
  raise ExceptionGroup(ValueError('a'), TypeError('b'))
except *ValueError:
  raise KeyError('x')

# would result in:
#
#   ExceptionGroup(
#     KeyError('x'),
#     TypeError('b')
#   )
```

**Comment by iritkatriel** [comment]
I'm closing this because I think we settled on preserving the structure of an EG throughout, and we don't provide any iteration/flattening apis for now (we can reconsider when a use case for them turns up).
